# Generated by Django 4.2.4 on 2023-08-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_ledger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensecategory',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
