# Generated by Django 4.2.4 on 2023-08-27 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_ledger', '0002_expensecategory_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensecategory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
