# Generated by Django 4.2.4 on 2023-08-23 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_ledger', '0002_alter_transaction_date_delete_expenseitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
