# Generated by Django 4.2.4 on 2023-09-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_ledger', '0003_alter_operation_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='tag',
        ),
        migrations.AddField(
            model_name='operation',
            name='tag',
            field=models.ManyToManyField(blank=True, to='core_ledger.tag'),
        ),
    ]
